### ISSUE TITLE
Invalid app name LDA

### ISSUE THREAD

**Issue by ashrafuzzaman** [EmergentOrder/template-scala-topic-model-LDA#2]
Ran,

``` bash
pio train
```

Got

``` bash
[INFO] [Console$] Using existing engine manifest JSON at /Users/newscred/projects/recommendation/predictionio/template-scala-topic-model-LDA/manifest.json
[INFO] [Runner$] Submission command: /Users/newscred/PredictionIO/vendors/spark-1.5.1/bin/spark-submit --class io.prediction.workflow.CreateWorkflow --jars file:/Users/newscred/projects/recommendation/predictionio/template-scala-topic-model-LDA/target/scala-2.10/template-scala-topic-model-LDA-assembly-0.1-SNAPSHOT-deps.jar,file:/Users/newscred/projects/recommendation/predictionio/template-scala-topic-model-LDA/target/scala-2.10/template-scala-topic-model-lda_2.10-0.1-SNAPSHOT.jar --files file:/Users/newscred/PredictionIO/conf/log4j.properties,file:/Users/newscred/PredictionIO/vendors/hbase-1.0.0/conf/hbase-site.xml --driver-class-path /Users/newscred/PredictionIO/conf:/Users/newscred/PredictionIO/vendors/hbase-1.0.0/conf file:/Users/newscred/PredictionIO/lib/pio-assembly-0.9.5.jar --engine-id IcHmmyTztI0uWcTXgZOW9AhUooR9OC5i --engine-version 94647ec8adf83e6daea0dc67bdcf4f5152c256dc --engine-variant file:/Users/newscred/projects/recommendation/predictionio/template-scala-topic-model-LDA/engine.json --verbosity 0 --json-extractor Both --env PIO_STORAGE_SOURCES_HBASE_TYPE=hbase,PIO_ENV_LOADED=1,PIO_STORAGE_REPOSITORIES_METADATA_NAME=pio_meta,PIO_FS_BASEDIR=/Users/newscred/.pio_store,PIO_STORAGE_SOURCES_HBASE_HOME=/Users/newscred/PredictionIO/vendors/hbase-1.0.0,PIO_HOME=/Users/newscred/PredictionIO,PIO_FS_ENGINESDIR=/Users/newscred/.pio_store/engines,PIO_STORAGE_SOURCES_LOCALFS_PATH=/Users/newscred/.pio_store/models,PIO_STORAGE_SOURCES_ELASTICSEARCH_TYPE=elasticsearch,PIO_STORAGE_REPOSITORIES_METADATA_SOURCE=ELASTICSEARCH,PIO_STORAGE_REPOSITORIES_MODELDATA_SOURCE=LOCALFS,PIO_STORAGE_REPOSITORIES_EVENTDATA_NAME=pio_event,PIO_STORAGE_SOURCES_ELASTICSEARCH_HOME=/Users/newscred/PredictionIO/vendors/elasticsearch-1.4.4,PIO_FS_TMPDIR=/Users/newscred/.pio_store/tmp,PIO_STORAGE_REPOSITORIES_MODELDATA_NAME=pio_model,PIO_STORAGE_REPOSITORIES_EVENTDATA_SOURCE=HBASE,PIO_CONF_DIR=/Users/newscred/PredictionIO/conf,PIO_STORAGE_SOURCES_LOCALFS_TYPE=localfs
[INFO] [Engine] Extracting datasource params...
[INFO] [WorkflowUtils$] No 'name' is found. Default empty String will be used.
[INFO] [Engine] Datasource params: (,DataSourceParams(LDA,None))
[INFO] [Engine] Extracting preparator params...
[INFO] [Engine] Preparator params: (,Empty)
[INFO] [Engine] Extracting serving params...
[INFO] [Engine] Serving params: (,Empty)
[INFO] [Remoting] Starting remoting
[INFO] [Remoting] Remoting started; listening on addresses :[akka.tcp://sparkDriver@192.168.1.31:56758]
[WARN] [MetricsSystem] Using default name DAGScheduler for source because spark.app.id is not set.
[INFO] [Engine$] EngineWorkflow.train
[INFO] [Engine$] DataSource: com.newscred.DataSource@36510e73
[INFO] [Engine$] Preparator: com.newscred.Preparator@5ba1b62e
[INFO] [Engine$] AlgorithmList: List(com.newscred.LDAAlgorithm@7d7ceca8)
[INFO] [Engine$] Data sanity check is on.
[ERROR] [Common$] Invalid app name LDA
Exception in thread "main" java.lang.IllegalArgumentException: Invalid app name LDA
    at io.prediction.data.store.Common$$anonfun$appNameToId$2.apply(Common.scala:47)
    at io.prediction.data.store.Common$$anonfun$appNameToId$2.apply(Common.scala:45)
    at scala.Option.getOrElse(Option.scala:120)
    at io.prediction.data.store.Common$.appNameToId(Common.scala:45)
    at io.prediction.data.store.PEventStore$.aggregateProperties(PEventStore.scala:103)
    at com.newscred.DataSource.readTraining(DataSource.scala:35)
    at com.newscred.DataSource.readTraining(DataSource.scala:22)
    at io.prediction.controller.PDataSource.readTrainingBase(PDataSource.scala:37)
    at io.prediction.controller.Engine$.train(Engine.scala:640)
    at io.prediction.controller.Engine.train(Engine.scala:174)
    at io.prediction.workflow.CoreWorkflow$.runTrain(CoreWorkflow.scala:65)
    at io.prediction.workflow.CreateWorkflow$.main(CreateWorkflow.scala:247)
    at io.prediction.workflow.CreateWorkflow.main(CreateWorkflow.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:674)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

I have no clue what I am doing wrong.

**Comment by ashrafuzzaman** [comment]
My bad. I created the app with another name. Closing this issue
