### ISSUE TITLE
Error during query

### ISSUE THREAD

**Issue by Christophy** [EmergentOrder/template-scala-topic-model-LDA#6]
build,train,deploy all good. but failed in query. I tried both spark 1.5.1 and 1.6.1, still won't work.
I tried to locate the error and find the error only happens when I use DistributedLDAModel.describeTopics in the predict method. the same error will not occur if it is used in the predict method. 
Thanks a lot
`Stack Trace:
java.lang.IllegalStateException: SparkContext has been shutdown
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1824)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1952)
        at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:1025)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
        at org.apache.spark.rdd.RDD.reduce(RDD.scala:1007)
        at org.apache.spark.mllib.clustering.DistributedLDAModel.describeTopics(LDAModel.scala:573)
        at com.stc.LDAAlgorithm.predict(LDAAlgorithm.scala:57)
        at com.stc.LDAAlgorithm.predict(LDAAlgorithm.scala:36)
        at io.prediction.controller.PAlgorithm.predictBase(PAlgorithm.scala:73)
        at io.prediction.workflow.ServerActor$$anonfun$24$$anonfun$25.apply(CreateServer.scala:536)
        at io.prediction.workflow.ServerActor$$anonfun$24$$anonfun$25.apply(CreateServer.scala:535)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at io.prediction.workflow.ServerActor$$anonfun$24.apply(CreateServer.scala:535)
        at io.prediction.workflow.ServerActor$$anonfun$24.apply(CreateServer.scala:513)
        at spray.routing.ApplyConverterInstances$$anon$22$$anonfun$apply$1.apply(ApplyConverterInstances.scala:25)
        at spray.routing.ApplyConverterInstances$$anon$22$$anonfun$apply$1.apply(ApplyConverterInstances.scala:24)
        at spray.routing.ConjunctionMagnet$$anon$1$$anon$2$$anonfun$happly$1$$anonfun$apply$1.apply(Directive.scala:38)
        at spray.routing.ConjunctionMagnet$$anon$1$$anon$2$$anonfun$happly$1$$anonfun$apply$1.apply(Directive.scala:37)
        at spray.routing.directives.BasicDirectives$$anon$1.happly(BasicDirectives.scala:26)
        at spray.routing.ConjunctionMagnet$$anon$1$$anon$2$$anonfun$happly$1.apply(Directive.scala:37)
        at spray.routing.ConjunctionMagnet$$anon$1$$anon$2$$anonfun$happly$1.apply(Directive.scala:36)
        at spray.routing.directives.BasicDirectives$$anon$2.happly(BasicDirectives.scala:79)
        at spray.routing.Directive$$anon$7$$anonfun$happly$4.apply(Directive.scala:86)
        at spray.routing.Directive$$anon$7$$anonfun$happly$4.apply(Directive.scala:86)
        at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
        at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
        at spray.routing.directives.ExecutionDirectives$$anonfun$detach$1$$anonfun$apply$7$$anonfun$apply$3.apply$mcV$sp(ExecutionDirectives.scala:89)
        at spray.routing.directives.ExecutionDirectives$$anonfun$detach$1$$anonfun$apply$7$$anonfun$apply$3.apply(ExecutionDirectives.scala:89)
        at spray.routing.directives.ExecutionDirectives$$anonfun$detach$1$$anonfun$apply$7$$anonfun$apply$3.apply(ExecutionDirectives.scala:89)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
`

**Comment by EmergentOrder** [comment]
Fixed this in master.

**Comment by Christophy** [comment]
@EmergentOrder 
Thanks a lot . Tested in spark local mode and the bug is now gone. I noticed you saved the LDAmodel and other things in the tmp folder. will this still work if I am in a cluster context, say, spark stand alone mode and hadoop?

**Comment by EmergentOrder** [comment]
We are using DistributedLDAModel here, and looking at the Spark source for it, it is using org.apache.hadoop.fs.Path , which means in local mode it should save to local FS and in cluster mode it should save to HDFS. So should work either way.
